apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-example
  description: An example component discovered via GitHub integration
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: guest